layout_spectrum: 1
typography_spectrum: 0.4787234
color:
  lightness: 0.7617021
  brandStrength: 0.5212766
  saturation: 0.7170213
  rhythmicContrast: 0.406383
  brandColors:
    - '#0D0C0C'
    - '#665C54'
    - '#FFFC4B'
    - '#E89C30'
    - '#FEFFFF'
name: The Foodways Design Collaborative
