name: The Foodways Design Collaborative
favicon: null
layout_spectrum: 0
typography_spectrum: 0.87603
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
title: The FDC
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#050306'
    - '#f7f7f7'
    - '#544c3b'
    - '#bb7400'
    - '#ffae00'
  brandStrength: 0.5
  lightness: 0.6875
  saturation: 0.3125
  rhythmicContrast: 0.5
purpose: []
