name: The Foodways Design Collaborative
favicon: null
layout_spectrum: 0
typography_spectrum: 0.2659574
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
title: The FDC
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3a3a3c'
    - '#3c3c3c'
    - '#404040'
    - '#333333'
    - '#000000'
  brandStrength: 0.5212766
  lightness: 0.3978723
  saturation: 0.7170213
  rhythmicContrast: 0.2957447
purpose: []
